name: package-extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "extension/**"
      - ".github/workflows/package-extension.yml"

jobs:
  build:
    name: Build unsigned bundle
    runs-on: ubuntu-latest
    environment: "Default"
    permissions:
      contents: write
    env:
      AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
      AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web-ext
        run: npm install --global web-ext

      - name: Build unsigned archive
        run: web-ext build --source-dir ./extension --artifacts-dir ./web-ext-artifacts

      - name: Upload unsigned artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontpage-extension-unsigned
          path: web-ext-artifacts/**

      - name: Sign using AMO (optional)
        env:
          WEB_EXT_API_KEY: ${{ env.AMO_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ env.AMO_JWT_SECRET }}
          WEB_EXT_ID: frontpage-submitter@example.com
        run: |
          if [ -z "${WEB_EXT_API_KEY}" ] || [ -z "${WEB_EXT_API_SECRET}" ]; then
            echo "AMO credentials not provided. Skipping signing step."
            exit 0
          fi
          web-ext sign \
            --channel=unlisted \
            --source-dir ./extension \
            --artifacts-dir ./web-ext-artifacts

      - name: Upload signed artifact (optional)
        if: ${{ hashFiles('web-ext-artifacts/*.xpi') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: frontpage-extension-signed
          path: web-ext-artifacts/*.xpi

      - name: Capture version info
        run: |
          VERSION=$(node -pe "require('./extension/manifest.json').version")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG=v${VERSION}-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Frontpage Submitter ${{ env.VERSION }} (build ${{ github.run_number }})
          draft: false
          prerelease: true
          generate_release_notes: false
          files: |
            web-ext-artifacts/*.zip
            web-ext-artifacts/*.xpi
          fail_on_unmatched_files: false
